/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import static hospital.management.system.environment.client_address_doc;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.json.JSONException;

/**
 *
 * @author Kaviraj
 */
public class myPatients extends javax.swing.JFrame {

    /**
     * Creates new form myPatients
     */
    DefaultTableModel model;

    public client_doctor doc1;
    public int port = environment.doctor_port;

    public myPatients() throws IOException, SocketException, UnknownHostException, RemoteException, SQLException, NotBoundException, ClassNotFoundException, JSONException, JSONException {
        initComponents();

        //this will set the frame to maximised size
        this.setExtendedState(this.getExtendedState() | myPatients.MAXIMIZED_BOTH);

        client_doctor doc = new client_doctor(patientsTbl);
        doc1 = doc;

        //setting table model
        doc1.setMyTable();

        //table properties
        patientsTbl.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 24));
        patientsTbl.getTableHeader().setOpaque(true);
        patientsTbl.getTableHeader().setBackground(new Color(0, 51, 153));
        patientsTbl.getTableHeader().setForeground(new Color(0, 51, 153));
        patientsTbl.setBackground(new Color(0, 51, 153, 180));

        doc1.refresh();

        int PORT = port;
        System.setProperty("java.rmi.server.hostname", client_address_doc);
        Registry r2 = LocateRegistry.createRegistry(PORT);
        rtImplCheckup pat;
        pat = new rtImplCheckup(doc1);

        r2.rebind("RealTimeCheckupService", pat);
        System.out.println("Server from doc running ! ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientsMenu = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        logLbl = new javax.swing.JLabel();
        refreshPanel = new javax.swing.JPanel();
        refreshLbl = new javax.swing.JLabel();
        middlePanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        logoLbl = new javax.swing.JLabel();
        mainPatientsPanel = new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    myPatients.class.getResource("/Picture_icon/checkupbg.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };
        titleLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientsTbl = new javax.swing.JTable();
        editPanel = new javax.swing.JPanel();
        editBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        patientsMenu.setBackground(new java.awt.Color(255, 102, 153));
        patientsMenu.setPreferredSize(new java.awt.Dimension(981, 72));
        patientsMenu.setLayout(new java.awt.GridLayout(1, 3));

        buttonsPanel.setBackground(new java.awt.Color(0, 51, 153));

        homePanel.setBackground(new java.awt.Color(0, 51, 153));
        homePanel.setPreferredSize(new java.awt.Dimension(150, 72));
        homePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homePanelMouseExited(evt);
            }
        });
        homePanel.setLayout(new java.awt.BorderLayout());

        logLbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        logLbl.setForeground(new java.awt.Color(255, 255, 255));
        logLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/log.png"))); // NOI18N
        logLbl.setText("Log Out");
        logLbl.setAlignmentX(0.5F);
        logLbl.setMaximumSize(new java.awt.Dimension(500, 32));
        logLbl.setPreferredSize(new java.awt.Dimension(200, 32));
        logLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logLblMouseExited(evt);
            }
        });
        homePanel.add(logLbl, java.awt.BorderLayout.CENTER);

        refreshPanel.setBackground(new java.awt.Color(0, 51, 153));
        refreshPanel.setPreferredSize(new java.awt.Dimension(150, 72));
        refreshPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshPanelMouseExited(evt);
            }
        });
        refreshPanel.setLayout(new java.awt.BorderLayout());

        refreshLbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        refreshLbl.setForeground(new java.awt.Color(255, 255, 255));
        refreshLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refreshLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/refresg.png"))); // NOI18N
        refreshLbl.setText("Refresh");
        refreshLbl.setToolTipText("");
        refreshLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshLblMouseExited(evt);
            }
        });
        refreshPanel.add(refreshLbl, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(refreshPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        patientsMenu.add(buttonsPanel);

        middlePanel.setBackground(new java.awt.Color(0, 51, 153));
        middlePanel.setPreferredSize(new java.awt.Dimension(50, 50));
        middlePanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout middlePanelLayout = new javax.swing.GroupLayout(middlePanel);
        middlePanel.setLayout(middlePanelLayout);
        middlePanelLayout.setHorizontalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        middlePanelLayout.setVerticalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        patientsMenu.add(middlePanel);

        logoPanel.setBackground(new java.awt.Color(0, 51, 153));
        logoPanel.setPreferredSize(new java.awt.Dimension(50, 50));

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/snake.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addContainerGap(523, Short.MAX_VALUE)
                .addComponent(logoLbl)
                .addGap(38, 38, 38))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addComponent(logoLbl)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        patientsMenu.add(logoPanel);

        getContentPane().add(patientsMenu, java.awt.BorderLayout.PAGE_START);

        mainPatientsPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPatientsPanel.setLayout(new javax.swing.BoxLayout(mainPatientsPanel, javax.swing.BoxLayout.Y_AXIS));

        titleLbl.setBackground(new java.awt.Color(255, 255, 255));
        titleLbl.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 51, 153));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("My Patients");
        titleLbl.setAlignmentX(0.5F);
        titleLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleLbl.setMaximumSize(new java.awt.Dimension(300, 47));
        titleLbl.setMinimumSize(new java.awt.Dimension(100, 47));
        titleLbl.setOpaque(true);
        titleLbl.setPreferredSize(new java.awt.Dimension(300, 100));
        titleLbl.setRequestFocusEnabled(false);
        mainPatientsPanel.add(titleLbl);

        patientsTbl.setBackground(new java.awt.Color(255, 255, 255));
        patientsTbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        patientsTbl.setForeground(new java.awt.Color(255, 255, 255));
        patientsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Checkup ID", "Date", "Surname", "Name", "Reason", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientsTbl.setFocusable(false);
        patientsTbl.setPreferredSize(new java.awt.Dimension(200, 750));
        patientsTbl.setRowHeight(50);
        patientsTbl.setRowMargin(0);
        patientsTbl.setSelectionBackground(new java.awt.Color(255, 255, 255));
        patientsTbl.setSelectionForeground(new java.awt.Color(0, 51, 153));
        patientsTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        patientsTbl.setShowHorizontalLines(false);
        patientsTbl.setShowVerticalLines(false);
        patientsTbl.getTableHeader().setReorderingAllowed(false);
        patientsTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientsTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(patientsTbl);

        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());

        mainPatientsPanel.add(jScrollPane1);

        editPanel.setBackground(new java.awt.Color(255, 255, 255));
        editPanel.setOpaque(false);
        editPanel.setPreferredSize(new java.awt.Dimension(1899, 40));
        editPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        editBtn.setBackground(new java.awt.Color(0, 51, 153));
        editBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/edit.png"))); // NOI18N
        editBtn.setText("Edit Diagnosis");
        editBtn.setAlignmentX(Component.CENTER_ALIGNMENT);
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editBtnMouseExited(evt);
            }
        });
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        editPanel.add(editBtn);

        mainPatientsPanel.add(editPanel);

        getContentPane().add(mainPatientsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshPanelMouseEntered
        // TODO add your handling code here:
        refreshPanel.setBackground(Color.white);
        refreshLbl.setForeground(new Color(0, 51, 153));

    }//GEN-LAST:event_refreshPanelMouseEntered

    private void refreshPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshPanelMouseExited
        // TODO add your handling code here:
        refreshPanel.setBackground(new Color(0, 51, 153));
        refreshLbl.setForeground(Color.white);
    }//GEN-LAST:event_refreshPanelMouseExited

    private void refreshLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLblMouseEntered
        // TODO add your handling code here:
        refreshPanel.setBackground(Color.white);
        refreshLbl.setForeground(new Color(0, 51, 153));
    }//GEN-LAST:event_refreshLblMouseEntered

    private void refreshLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLblMouseExited
        // TODO add your handling code here:
        refreshPanel.setBackground(new Color(0, 51, 153));
        refreshLbl.setForeground(Color.white);
    }//GEN-LAST:event_refreshLblMouseExited

    private void homePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseEntered
        // TODO add your handling code here:
        homePanel.setBackground(Color.white);
        logLbl.setForeground(new Color(0, 51, 153));

    }//GEN-LAST:event_homePanelMouseEntered

    private void homePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseExited
        // TODO add your handling code here:
        homePanel.setBackground(new Color(0, 51, 153));
        logLbl.setForeground(Color.white);
    }//GEN-LAST:event_homePanelMouseExited

    private void logLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logLblMouseEntered
        // TODO add your handling code here:
        homePanel.setBackground(Color.white);
        logLbl.setForeground(new Color(0, 51, 153));
    }//GEN-LAST:event_logLblMouseEntered

    private void logLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logLblMouseExited
        // TODO add your handling code here:
        homePanel.setBackground(new Color(0, 51, 153));
        logLbl.setForeground(Color.white);
    }//GEN-LAST:event_logLblMouseExited

    private void refreshLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLblMouseClicked
        try {
            //call refresh method to load values from server
            doc1.refresh();

        } catch (UnknownHostException ex) {
            Logger.getLogger(myPatients.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(myPatients.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(myPatients.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(myPatients.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshLblMouseClicked

    private void patientsTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientsTblMouseClicked
        // TODO add your handling code here:
        int col = patientsTbl.columnAtPoint(evt.getPoint());
    }//GEN-LAST:event_patientsTblMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        int row = patientsTbl.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row first!");
        } else {
            String idval = patientsTbl.getModel().getValueAt(row, 0).toString();
            String dateval = patientsTbl.getModel().getValueAt(row, 1).toString();
            String snameval = patientsTbl.getModel().getValueAt(row, 2).toString();
            String nameval = patientsTbl.getModel().getValueAt(row, 3).toString();
            String reasonval = patientsTbl.getModel().getValueAt(row, 4).toString();

            diagnosticScreen ds = new diagnosticScreen(nameval, snameval, reasonval, dateval, idval,doc1);
            ds.setVisible(true);

        }

    }//GEN-LAST:event_editBtnActionPerformed

    private void editBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseEntered
        // TODO add your handling code here:
        editBtn.setBackground(Color.white);
        editBtn.setForeground(new Color(0, 51, 153));
    }//GEN-LAST:event_editBtnMouseEntered

    private void editBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseExited
        // TODO add your handling code here:
        editBtn.setBackground(new Color(0, 51, 153));
        editBtn.setForeground(Color.white);
    }//GEN-LAST:event_editBtnMouseExited

    private void logLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logLblMouseClicked
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myPatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myPatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myPatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myPatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    new myPatients().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(myPatients.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(myPatients.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(myPatients.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(myPatients.class.getName()).log(Level.SEVERE, null, ex);
                } catch (JSONException ex) {
                    Logger.getLogger(myPatients.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel editPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logLbl;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel mainPatientsPanel;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JPanel patientsMenu;
    private javax.swing.JTable patientsTbl;
    private javax.swing.JLabel refreshLbl;
    private javax.swing.JPanel refreshPanel;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
